global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pollution-prediction-api'
    static_configs:
      - targets: ['host.docker.internal:8001']
    metrics_path: '/metrics'
    scheme: 'http'
